name: Ubuntu

on:
  push:
    branches: [ main ]
    tags: 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/') || !contains(github.event.head_commit.message, '[skip CI]')"
    steps:
      - uses: actions/checkout@v2
      - name: build-test
        run: ｜
          sudo apt install -y lua5.4 liblua5.4-dev luarocks
          sudo luarocks --lua-version 5.4 install busted
          make test
      - name: pack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make clean
          make release
          (cd bin/release && zip -r ../../yue-linux-x86_64.zip ./yue)
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./yue-linux-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
